routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/keadaan-opt', 'HomeController@keadaanOpt')->name('keadaan-opt');
Route::get('/data-petugas', 'HomeController@dataPetugas')->name('data-petugas');
Route::get('/news', 'HomeController@news')->name('news');
Route::get('/news-detail/{url}', 'HomeController@newsDetail')->name('news-detail');


Route::group(['as' =>'admin.', 'namespace' => '\App\Http\Controllers\Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('', 'DashboardController@index')->name('index');
    Route::get('profile', 'ProfileController@profile')->name('profile');
    Route::post('profile/update', 'ProfileController@update')->name('profile.update');

    Route::get('sub-district', 'JsonController@subDistrict')->name('json.sub-district');
    Route::get('opt', 'JsonController@opt')->name('json.opt');
    Route::get('commodity', 'JsonController@commodity')->name('json.commodity');
    Route::get('village', 'JsonController@village')->name('json.village');

    Route::group([
        'namespace' => '\App\Http\Controllers\Admin\UserManagement', 
        'as' =>'user-management.', 'prefix' => 'user-management'], function () {
            
            Route::group(['as' =>'user.', 'prefix' => 'user'], function () {
                Route::get('', 'UserController@index')->name('index');       
                Route::get('create', 'UserController@create')->name('create');
                Route::post('store', 'UserController@store')->name('store');
                Route::get('{id}/edit', 'UserController@edit')->name('edit');
                Route::post('{id}/update', 'UserController@update')->name('update');
                Route::get('{id}/delete', 'UserController@delete')->name('delete');
            });
            Route::group(['as' =>'permission.', 'prefix' => 'permission'], function () {
                Route::get('', 'PermissionController@index')->name('index');       
                Route::get('create', 'PermissionController@create')->name('create');
                Route::post('store', 'PermissionController@store')->name('store');
                Route::get('{id}/edit', 'PermissionController@edit')->name('edit');
                Route::post('{id}/update', 'PermissionController@update')->name('update');
                Route::get('{id}/delete', 'PermissionController@delete')->name('delete');
            });

            Route::group(['as' =>'role.', 'prefix' => 'role'], function () {
                Route::get('', 'RoleController@index')->name('index');       
                Route::get('create', 'RoleController@create')->name('create');
                Route::post('store', 'RoleController@store')->name('store');
                Route::get('{id}/edit', 'RoleController@edit')->name('edit');
                Route::post('{id}/update', 'RoleController@update')->name('update');
                Route::get('{id}/delete', 'RoleController@delete')->name('delete');
            });
    });

    Route::group([
        'namespace' => '\App\Http\Controllers\Admin\DataMaster', 
        'as' =>'datamaster.', 'prefix' => 'data-master'], function () {

            Route::group(['as' =>'commodity.', 'prefix' => 'commodity'], function () {
                Route::get('', 'CommodityController@index')->name('index');       
                Route::get('create', 'CommodityController@create')->name('create');
                Route::post('store', 'CommodityController@store')->name('store');
                Route::get('{id}/edit', 'CommodityController@edit')->name('edit');
                Route::post('{id}/update', 'CommodityController@update')->name('update');
                Route::get('{id}/delete', 'CommodityController@delete')->name('delete');
                Route::post('import', 'CommodityController@import')->name('import');
            });

            Route::group(['as' =>'distraction.', 'prefix' => 'distraction'], function () {
                Route::get('', 'DistractionController@index')->name('index');       
                Route::get('create', 'DistractionController@create')->name('create');
                Route::post('store', 'DistractionController@store')->name('store');
                Route::get('{id}/edit', 'DistractionController@edit')->name('edit');
                Route::post('{id}/update', 'DistractionController@update')->name('update');
                Route::get('{id}/delete', 'DistractionController@delete')->name('delete');
                Route::post('import', 'DistractionController@import')->name('import');

            });

            Route::group(['as' =>'sub-district.', 'prefix' => 'sub-district'], function () {
                Route::get('', 'SubdistrictController@index')->name('index');       
                Route::get('create', 'SubdistrictController@create')->name('create');
                Route::post('store', 'SubdistrictController@store')->name('store');
                Route::get('{id}/edit', 'SubdistrictController@edit')->name('edit');
                Route::post('{id}/update', 'SubdistrictController@update')->name('update');
                Route::get('{id}/delete', 'SubdistrictController@delete')->name('delete');
            });

            Route::group(['as' =>'news.', 'prefix' => 'news'], function () {
                Route::get('', 'NewsController@index')->name('index');       
                Route::get('create', 'NewsController@create')->name('create');
                Route::post('store', 'NewsController@store')->name('store');
                Route::get('{id}/edit', 'NewsController@edit')->name('edit');
                Route::post('{id}/update', 'NewsController@update')->name('update');
                Route::get('{id}/delete', 'NewsController@delete')->name('delete');
                Route::post('import', 'NewsController@import')->name('import');

            });
    });

    Route::group(['as' =>'import.', 'prefix' => 'import'], function () {
        Route::get('perkebunan', 'ImportController@importPerkebunan')->name('importPerkebunan'); 
        Route::post('import-perkebunan', 'ImportController@storeImportPerkebunan')->name('store-import-perkebunan');
        Route::get('tanaman-pangan', 'ImportController@importTanamanPangan')->name('tanaman-pangan'); 
        Route::post('import-tanaman-pangan', 'ImportController@storeImportTanamanPangan')->name('store-import-tanaman-pangan');
        Route::get('holtikultura', 'ImportController@importHoltikultura')->name('holtikultura'); 
        Route::post('import-holtikultura', 'ImportController@storeImportHoltikultura')->name('store-import-holtikultura');

    });

    Route::group([
        'namespace' => '\App\Http\Controllers\Admin\Data', 
        'as' =>'data.', 'prefix' => 'data'], function () {

            Route::group(['as' =>'data-report.', 'prefix' => 'data-report'], function () {
                Route::get('', 'DataReportController@index')->name('index');       
                Route::get('create', 'DataReportController@create')->name('create');
                Route::post('create-1', 'DataReportController@createStep1')->name('create-step-1');
                Route::post('create-final', 'DataReportController@preview')->name('create-final');
                Route::get('store', 'DataReportController@store')->name('store');
            });
    });

    Route::group([
        'namespace' => '\App\Http\Controllers\Admin'], function () {

            Route::group(['as' =>'statistic.', 'prefix' => 'statistic'], function () {
                Route::get('', 'StatisticController@index')->name('index');       
                Route::get('{id}/detail', 'StatisticController@detail')->name('detail');       
            });

            Route::group(['as' =>'report.', 'prefix' => 'report'], function () {

                Route::group(['as' =>'perkebunan.', 'prefix' => 'perkebunan'], function () {
                    Route::get('', 'ReportPlantationController@index')->name('index');       
                    Route::get('{id}/detail', 'ReportPlantationController@detail')->name('detail');
                    Route::get('{id}/edit', 'ReportPlantationController@edit')->name('edit');
                    Route::get('{id}/delete', 'ReportPlantationController@delete')->name('delete');
                    Route::post('{id}/update', 'ReportPlantationController@update')->name('update');
                    Route::get('{id}/detail-print', 'ReportPlantationController@detailPrint')->name('detail-print');
                    Route::get('{id}/detail-print-pdf', 'ReportPlantationController@detailPrintPdf')->name('detail-print-pdf');
                    Route::get('print', 'ReportPlantationController@print')->name('print');
                    Route::get('xls', 'ReportPlantationController@xls')->name('xls');
                    Route::get('csv', 'ReportPlantationController@csv')->name('csv');
                    Route::get('pdf', 'ReportPlantationController@pdf')->name('pdf');

                    Route::group(['as' =>'dpi.', 'prefix' => 'dpi'], function () {
                        Route::get('', 'ReportPlantationDpiController@index')->name('index');       
                        Route::get('{id}/detail', 'ReportPlantationDpiController@detail')->name('detail');
                        Route::get('{id}/edit', 'ReportPlantationDpiController@edit')->name('edit');

resources/views/data/input-data.blade.php
@extends('layouts.master')

@section('css')
    <link href="{{ URL::asset('assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet" />
@endsection

@php
    use \App\Http\Constants\TypeCommodity;
    $user = logged_in_user();
@endphp


@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        Home
                    </li>
                    <li class="breadcrumb-item">
                        Input Data
                    </li>
                    <li class="breadcrumb-item active">
                        Laporan
                    </li>
                </ol>
                <h4>Selamat Datang</h4>
                <h6>Silahkan Melakukan inputan data pada form dibawah</h6>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card m-b-20">
                <div class="card-body">
                    <h4 class="mt-0 mb-4 header-title">LAPORAN SERANGAN ORGANISME PENGANGGU TUMBUHAN (OPT)</h4>
                    <form action="{{ route('admin.data.data-report.create-step-1') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label class="control-label font-bold label-green">Periode</label>
                                <div>
                                    <div class="input-group">
                                        <input type="text" class="form-control periode" autocomplete="off" required name="date" placeholder="Periode" id="datepicker-autoclose">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="mdi mdi-calendar"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 form-group">
                                <div class="form-group">
                                    <label class="control-label font-bold label-green">Kategori</label>
                                    <select class="form-control select2 type" required name="type_commodity" data-placeholder="Pilih Data">
                                        <option value=""></option>
                                        @foreach (TypeCommodity::labels() as $key => $item)
                                            <option value="{{ $key }}">{{ $item }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-lg-6 form-group" id="tanaman-pangan" style="display: none">
                                <div class="form-group">
                                    <label class="control-label font-bold label-green">Tipe OPT Tanaman Pangan</label>
                                    <select class="form-control select2" name="type_opt_pangan" data-placeholder="Pilih Data">
                                        <option value=""></option>
                                        <option value="1">Data OPT</option>
                                        <option value="2">Data OPT Banjir</option>
                                        <option value="3">Data Opt Kekeringan</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-lg-6 form-group" id="hortikultura" style="display: none">
                                <div class="form-group">
                                    <label class="control-label font-bold label-green">Tipe OPT Hortikultura</label>
                                    <select class="form-control select2 type-hortikultura" name="type_opt_hortikultura" data-placeholder="Pilih Data">
                                        <option value=""></option>
                                        <option value="1">Data OPT</option>
                                        <option value="2">Data OPT Banjir</option>
                                        <option value="3">Data Opt Kekeringan</option>
                                    </select>
                                </div>
                            </div>


                        </div>
                        <div id="perkebunan" style="display: none">
                            
                            <div class="form-group">
                                <label class="control-label font-bold label-green">Tipe OPT Perkebunan</label>
                                <select class="form-control select2 type-perkebunan" name="type_opt_perkebunan" data-placeholder="Pilih Data">
                                    <option value=""></option>
                                    <option value="1">Data OPT</option>
                                    <option value="2">Data OPT DPI</option>
                                    <option value="3">Data Opt LKK</option>
                                </select>
                            </div>

                            <textarea name="description" id="laporan_editor" rows="10" cols="100" required>
                                <h3><strong>I. PENDAHULUAN</strong></h3>
    
                                <h3><strong>II. JENIS KEGIATAN</strong></h3>
    
                                <h3><strong>III. SARANA DAN PRASARANA</strong></h3>
    
                                <p>1. Persediaan Pestisida</p>
    
                                <p>2. Alat Pengendalian</p>
    
                                <h3><strong>IV. PENGGUNAAN PESTISIDA KIMIA, NABATI DAN APH</strong></h3>
    
                                <p>1. Penggunaan Pestisida Kimia</p>
    
                                <p>2. Penggunaan Pestisida Nabati</p>
    
                                <p>3. Penggunaan Agensia Hayati</p>
    
                                <h3><strong>V. PERMASALAHAN DAN PEMECAHANNYA</strong></h3>
    
                                <h3><strong>VI. RENCANA KEGIATAN BULAN SELANJUTNYA</strong></h3>
    
                            </textarea>
                        </div>
                        <div class="mt-4 text-right">
                            <button type="submit" class="btn btn-primary">Simpan & Lanjutkan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> <!-- container-fluid -->
@endsection

@push('styles')
<style>
    ::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
  color: #ccb9b9 !important;
  opacity: 1; /* Firefox */
}
</style>
@endpush

@push('scripts')
<!--Morris Chart-->
<script src="{{ URL::asset('assets/plugins/morris/morris.min.js')}}"></script>
<script src="{{ URL::asset('assets/plugins/raphael/raphael-min.js')}}"></script>

<script src="{{ URL::asset('assets/pages/dashboard.js')}}"></script>
<script src="{{ URL::asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
<script src="{{ URL::asset('assets/plugins/select2/js/select2.min.js')}}"></script>
<script>
    $(".select2").select2();

    $('.type').on('change', function(){
        var val = $(this).val();

        switch (val) {
            case '1':
                $('#tanaman-pangan').show();
                $('#hortikultura').hide();
                $('#perkebunan').hide();
                $(".type-pangan").prop('required',true);
                $(".type-hortikultura").prop('required',false);
                $(".type-perkebunan").prop('required',false);
                break;

            case '2':
                $('#tanaman-pangan').hide();
                $('#hortikultura').show();
                $('#perkebunan').hide();

                $(".type-pangan").prop('required',false);
                $(".type-perkebunan").prop('required',false);
                $(".type-hortikultura").prop('required',true);
                break;

            case '3':
                $('#tanaman-pangan').hide();
                $('#hortikultura').hide();
                $('#perkebunan').show();

                $(".type-perkebunan").prop('required',true);

                $(".type-pangan").prop('required',false);
                $(".type-hortikultura").prop('required',false);

                break;
        
            default:
                break;
        }

    });

    $(".periode").datepicker({
        autoclose: true,
        todayHighlight: true,
        minViewMode: 1,
        format: "yyyy-mm"
    });

    CKEDITOR.replace( 'Resolution', {
        height: 400
    } );

    // Replace the <textarea id="editor1"> with a CKEditor 4
    // instance, using default configuration.
    CKEDITOR.replace('laporan_editor');

    CKEDITOR.instances.editor1.on('change', function () {
        var data = CKEDITOR.instances.laporan_editor.getData();
    })

    document.querySelector('.custom-file-input').addEventListener('change', function (e) {
        var fileName = document.getElementById("myInput").files[0].name;
        $('.custom-file-label').text(fileName);
    })

</script>
@endpush

resources/views/data/preview.blade.php
@extends('layouts.master')

@section('css')
<link href="{{ URL::asset('assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}"
    rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet" />
@endsection

@php
    use \App\Http\Constants\TypeCommodity;
    use \App\Http\Constants\ControlArea;
    $user = logged_in_user();
@endphp


@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        Home
                    </li>
                    <li class="breadcrumb-item">
                        Input Data
                    </li>
                    <li class="breadcrumb-item active">
                        Preview Data
                    </li>
                </ol>
                <h4>Preview Data</h4>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card m-b-20">
                <div class="card-body">
                    <div class="form-group">
                        <table class="table table-bordered table-striped mb-0">
                            <tbody>
                                <tr>
                                    <td width="50%">Nama</td>
                                    <td>{{ $user->name }}</td>
                                </tr>
                                <tr>
                                    <td>Provinsi</td>
                                    <td>{{ optional($user->district)->name }}</td>
                                </tr>
                                <tr>
                                    <td>Kecamatan</td>
                                    <td>{{ resolve(\App\Repositories\Entities\SubDistrict::class)->where('id', $data['sub_district_id'])->first()->name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <td>Periode</td>
                                    <td>{{ date_view($data['date']) }}</td>
                                </tr>
                                <tr>
                                    <td>Kategori</td>
                                    <td>{{ TypeCommodity::label($data['type_commodity']) }}</td>
                                </tr>
                                <tr>
                                    <td>Komoditas</td>
                                    <td>{{ resolve(\App\Repositories\Entities\Commodity::class)->where('id', $data['commodity_id'])->first()->name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <td>Luas Pertanaman (ha)</td>
                                    <td>{{ $data['planting_area'] }}</td>
                                </tr>
                                <tr>
                                    @php
                                        $opt = resolve(\App\Repositories\Entities\Opt::class)->whereIn('id', ($data['opts'] ?? null))->pluck('name')->toArray() ?? [];
                                    @endphp
                                    <td>OPT</td>
                                    <td>{{ implode(', ', $opt) }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <label class="control-label text-uppercase font-14 mb-3 font-bold label-green">Intensitas Serangan</label>
                            <div class="form-group">
                                <table class="table table-bordered table-striped mb-0">
                                    <tbody>
                                        <tr>
                                            <td width="50%">Ringan</td>
                                            <td>{{ $data['itensity_attack_easy'] }}</td>
                                        </tr>
                                        <tr>
                                            <td>Berat</td>
                                            <td>{{ $data['itensity_attack_hard'] }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-12">
                            <label class="control-label text-uppercase font-14 mb-3 font-bold label-green">Luas Pengendalian</label>
                            <div class="form-group">
                                <table class="table table-bordered table-striped mb-0">
                                    <tbody>
                                        <tr>
                                            <td width="50%">ABPN</td>
                                            <td>{{ $data['control_area_apbn'] }}</td>
                                        </tr>
                                        <tr>
                                            <td width="50%">APBD I</td>
                                            <td>{{ $data['control_area_apbd_1'] }}</td>
                                        </tr>
                                        <tr>
                                            <td width="50%">APBD II</td>
                                            <td>{{ $data['control_area_apbd_2'] }}</td>
                                        </tr>
                                        <tr>
                                            <td width="50%">Masyarakat</td>
                                            <td>{{ $data['control_area_apbd_public'] }}</td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-12">
                            <label class="control-label text-uppercase font-14 mb-3 font-bold label-green">Cara Pengendalian</label>
                            <div class="form-group">
                                <table class="table table-bordered table-striped mb-0">
                                    <tbody>
                                        <tr>
                                            <td width="50%">
                                                @foreach ($data['control_areas'] as $item)
                                                    @php
                                                        $controlArea[] = ControlArea::label($item);
                                                    @endphp
                                                @endforeach
                                                {{ implode(', ', $controlArea) }}
                                            </td>
                                            <td>{{ $data['control_area_other'] ?? '-' }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-12">
                            <label class="control-label text-uppercase font-14 mb-3 font-bold label-green">Harga rata-rata / ton</label>
                            <div class="form-group">
                                <table class="table table-bordered table-striped mb-0">
                                    <tbody>
                                        <tr>
                                            <td>Rp. {{ $data['price_average'] }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="alert alert-danger l-h-23">
                                * mohon isi data dengan sebenar - benarnya dan cek kembali inputan data anda. Karena <span class="font-bold">data tidak bisa diedit</span> kembali. Terima Kasih.
                            </div>
                        </div>

                        <div class="col-12 text-right">
                            <a href="javascript:history.back()" class="btn btn-md-block btn-danger my-2">Kembali</a>
                            <a href="{{ route('admin.data.data-report.store') }}" onclick="return confirm('Anda Yakin Ingin Menyimpan data, data yang di input tidak bisa di edit kembali ?');"class="btn btn-md-block btn-primary my-2">Simpan Data</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div> <!-- container-fluid -->
@endsection

@push('script')
<script src="{{ URL::asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
<script src="{{ URL::asset('assets/plugins/select2/js/select2.min.js')}}"></script>
<script>
    // Select2
    $(".select2").select2();
    jQuery('#datepicker-autoclose').datepicker({
        format: 'dd/mm/yyyy',
        autoclose: true,
        todayHighlight: true
    });

</script>
@endpush